### PR TITLE
It seems like `PyObject_GetAttr` returns a borrowed reference

### PR DESCRIPTION
**Pull request by vladfolts**

### CODE REVIEW

**Comment by alabuzhev** [comment]
Huh?
> [PyObject_GetAttr](https://docs.python.org/3.11/c-api/object.html#c.PyObject_GetAttr)
> *Return value: New reference.*

**Comment by vladfolts** [comment]
> > _Return value: New reference._

Thanks for the link. It was not specified explicitly in the document that I googled. Still the problem is somewhere in between: `PyObject_GetAttr` -> `py::list` -> iterator -> `PyObject*` that becomes invalid while `py::list` with this element is still alive... Considering that this extra reference inc in the change helps it looks like `py::list` is GC'ed somehow...

**Comment by vladfolts** [comment]
OK, so the problem is in `py::list` not being actually alive... And that is because of Far calling`GetFilesW` with elements from `GetFindDataW` call _after_ it already called `FreeFindDataW`... I guess I don't have any choice other than to use a custom `FARPANELITEMFREECALLBACK`...

I'm closing this PR.

**Comment by alabuzhev** [comment]
> OK, so the problem is in `py::list` not being actually alive... And that is because of Far calling`GetFilesW` with elements from `GetFindDataW` call _after_ it already called `FreeFindDataW`

Do you have an example? I've faced something similar recently in a different context, it might be an overlook in Far worth fixing.

**Comment by vladfolts** [comment]
I'll prepare an updated "Hello World" and make a new PR.

**Pull request closed without merging**
